# Generated by Django 6.0.3 on 2026-03-27 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Epicenter Nexus', max_length=100)),
                ('site_tagline', models.CharField(default='Your Real-Time News Hub', max_length=200)),
                ('newsdata_api_key', models.CharField(blank=True, help_text='API key from newsdata.io', max_length=200)),
                ('newsapi_key', models.CharField(blank=True, help_text='API key from newsapi.org', max_length=200)),
                ('cache_ttl', models.IntegerField(default=180, help_text='Cache TTL in seconds')),
                ('auto_refresh_seconds', models.IntegerField(default=180, help_text='Auto-refresh interval in seconds')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('hero_banner', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('default_country', models.CharField(default='ke', help_text='Default country code (e.g. ke for Kenya)', max_length=5)),
                ('default_language', models.CharField(default='en', max_length=5)),
                ('footer_text', models.TextField(default='© 2026 Epicenter Nexus. Powered by 404Evans™')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_country', models.CharField(default='ke', max_length=5)),
                ('default_categories', models.CharField(blank=True, default='', help_text='Comma-separated list of preferred categories', max_length=500)),
                ('default_language', models.CharField(default='en', max_length=5)),
                ('saved_keywords', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
