# Generated by Django 6.0.3 on 2026-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currents_api_key',
            field=models.CharField(blank=True, help_text='API key from currentsapi.services', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gnews_api_key',
            field=models.CharField(blank=True, help_text='API key from gnews.io', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='thenewsapi_key',
            field=models.CharField(blank=True, help_text='API key from thenewsapi.com', max_length=200),
        ),
    ]
